let current=0,score=0,answered=false,timer=null,seconds=30,quizQuestions=[];
const $=id=>document.getElementById(id);
function filtered(){const s=$("subject").value,d=$("difficulty").value,c=$("company").value;return QUESTION_BANK.filter(q=>(s==="All Subjects"||q.subject===s)&&(d==="All Levels"||q.difficulty===d)&&(c==="All Companies"||q.company===c))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function supportive(ok){return ok?["Correct! Great job — keep the momentum going.","Excellent! Your placement preparation is getting stronger.","Nice work! Stay focused and keep going."][current%3]:["Don't worry — one mistake is part of learning. Read the explanation and try the next one.","Keep going! Review this concept and use it in the next question.","Good attempt. Learn from this one and move forward."][current%3]}
function start(){const f=filtered();if(!f.length){alert("No questions match these filters.");return}const n=+$("count").value;quizQuestions=shuffle(f).slice(0,n);current=0;score=0;$("quiz").classList.remove("hidden");$("result").classList.add("hidden");$("stats").innerHTML=`<span>${f.length.toLocaleString()} matching questions</span><span>1,200+ per subject</span><span>58 company styles</span><span>${+$("time").value===30?"30 seconds":+$("time").value===60?"1 minute":"2 minutes"} / question</span>`;show()}
function show(){answered=false;seconds=+$("time").value;clearInterval(timer);const q=quizQuestions[current];$("progress").textContent=`Question ${current+1} / ${quizQuestions.length}`;$("timer").textContent=`⏱ ${fmt(seconds)}`;$("bar").style.width=((current)/quizQuestions.length*100)+"%";$("qSubject").textContent=q.subject;$("qDiff").textContent=q.difficulty;$("qCompany").textContent=q.company+" style";$("question").textContent=q.question;$("feedback").innerHTML="";$("options").innerHTML=q.options.map(o=>`<button class="option">${o}</button>`).join("");document.querySelectorAll(".option").forEach(b=>b.onclick=()=>answer(b));$("next").textContent=current===quizQuestions.length-1?"Finish Quiz":"Next →";$("next").disabled=true;timer=setInterval(()=>{seconds--;$("timer").textContent=`⏱ ${fmt(seconds)}`;if(seconds<=0){clearInterval(timer);autoWrong()}},1000)}
function fmt(s){const m=Math.floor(s/60),sec=s%60;return m?`${m}:${String(sec).padStart(2,"0")}`:`${sec}s`}
function autoWrong(){if(answered)return;answered=true;const q=quizQuestions[current];$("feedback").innerHTML=`<div class="feedback bad"><b>⏰ Time's up.</b> ${supportive(false)}<br><br><b>Correct answer:</b> ${q.answer}<br>${q.explanation}</div>`;document.querySelectorAll(".option").forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add("correct")});$("next").disabled=false}
function answer(btn){if(answered)return;answered=true;clearInterval(timer);const q=quizQuestions[current],ok=btn.textContent===q.answer;if(ok){score++;btn.classList.add("correct")}else btn.classList.add("wrong");document.querySelectorAll(".option").forEach(b=>{b.disabled=true;if(b.textContent===q.answer)b.classList.add("correct")});$("feedback").innerHTML=`<div class="feedback ${ok?"good":"bad"}"><b>${supportive(ok)}</b><br><br><b>Correct answer:</b> ${q.answer}<br>${q.explanation}</div>`;$("next").disabled=false}
$("next").onclick=()=>{if(!answered)return;if(current<quizQuestions.length-1){current++;show()}else finish()}
function finish(){clearInterval(timer);$("quiz").classList.add("hidden");$("result").classList.remove("hidden");const pct=Math.round(score/quizQuestions.length*100);const msg=pct>=80?"Excellent placement practice!":pct>=60?"Good effort — review the missed concepts and try again.":"Keep practicing. Every attempt improves speed and accuracy.";localStorage.setItem("quizmasterLastScore",JSON.stringify({score,total:quizQuestions.length,pct,date:new Date().toISOString()}));$("result").innerHTML=`<h2>Quiz Complete 🎉</h2><p><b>${score} / ${quizQuestions.length}</b></p><h2>${pct}%</h2><p>${msg}</p><p>Time mode: ${+$("time").value===30?"30 seconds":+$("time").value===60?"1 minute":"2 minutes"} per question.</p><button onclick="location.reload()">Back to Quiz Setup</button>`}
$("start").onclick=start;$("themeBtn").onclick=()=>document.body.classList.toggle("dark");
